name: Quality

on:
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build the theme
        run: npm run theme
      - name: Run tests
        run: npm run test
